import type { Metadata } from 'next';
import {
  BRAND_COLOR,
  SITE_IMAGE_ALT,
  SITE_NAME,
  getTwitterHandle,
  isIndexingAllowed,
} from '@/lib/config/site';
import {
  APPLE_TOUCH_PNGS,
  FAVICON_ICO,
  FAVICON_PNGS,
  FAVICON_SVG,
  MASK_ICON_SVG,
  OG_IMAGE_SIZE,
  OG_IMAGE_TYPE,
  PWA_ICON_PNGS,
  pngSizes,
} from '@/lib/brand/assets';
import { hasPageCard, pageCardPath } from '@/lib/seo/ogPages';

/** The site-wide card generated by src/app/opengraph-image.tsx. */
export const OG_IMAGE = { url: '/opengraph-image', ...OG_IMAGE_SIZE, type: OG_IMAGE_TYPE, alt: SITE_IMAGE_ALT };

/**
 * The social card for a page: its own card for sidebar pages, otherwise the
 * site-wide card. Every page gets an image, so a share never shows a blank.
 */
export function ogImageFor(path: string, title: string) {
  if (!hasPageCard(path)) return OG_IMAGE;
  return { url: pageCardPath(path), ...OG_IMAGE_SIZE, type: OG_IMAGE_TYPE, alt: `${title} · ${SITE_NAME}` };
}

// Metadata merges shallowly, so a page that sets `openGraph` replaces the root
// layout's object, file-based image included. Every page spreads this to keep
// the shared fields.
export const baseOpenGraph = {
  type: 'website',
  siteName: SITE_NAME,
  locale: 'en_US',
  images: [OG_IMAGE],
} satisfies Metadata['openGraph'];

const twitterHandle = getTwitterHandle();

export const baseTwitter = {
  card: 'summary_large_image',
  ...(twitterHandle && { site: twitterHandle, creator: twitterHandle }),
} satisfies Metadata['twitter'];

/** For pages that show one lead or campaign: never index, never follow. */
export const PRIVATE_ROBOTS: Metadata['robots'] = {
  index: false,
  follow: false,
  googleBot: { index: false, follow: false },
};

/** Site-wide robots tag: noindex unless ALLOW_SEARCH_INDEXING=true (see isIndexingAllowed). */
export function siteRobots(): Metadata['robots'] {
  if (!isIndexingAllowed()) return PRIVATE_ROBOTS;
  return {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  };
}

const png = (file: { path: string; size: number }) => ({
  url: file.path,
  sizes: pngSizes(file),
  type: 'image/png',
});

/**
 * Every icon link tag. The files live in public/ and are generated by
 * `npm run brand:assets` (src/lib/brand/assets.ts lists them).
 */
export const BRAND_ICONS: Metadata['icons'] = {
  icon: [
    // sizes="32x32" (not "any") so Chrome picks the SVG over the ICO.
    { url: FAVICON_ICO.path, sizes: '32x32' },
    { url: FAVICON_SVG, type: 'image/svg+xml' },
    ...FAVICON_PNGS.filter((file) => file.path !== '/favicon.png').map(png),
    ...PWA_ICON_PNGS.filter((file) => [96, 192, 512].includes(file.size)).map(png),
  ],
  shortcut: [FAVICON_ICO.path],
  apple: APPLE_TOUCH_PNGS.filter((file) => file.path !== '/apple-touch-icon-180x180.png').map(png),
  other: [{ rel: 'mask-icon', url: MASK_ICON_SVG, color: BRAND_COLOR }],
};

interface PageSeo {
  /** Short page name; the root layout appends " · LeadForge". */
  title: string;
  description: string;
  /** Route path, used for the canonical link, og:url and the social card. */
  path: string;
  /** Use `title` as is, without the " · LeadForge" suffix. */
  absoluteTitle?: boolean;
}

/** Title, description, canonical URL, Open Graph and Twitter tags for one page. */
export function pageMetadata({ title, description, path, absoluteTitle = false }: PageSeo): Metadata {
  const fullTitle = absoluteTitle ? title : `${title} · ${SITE_NAME}`;
  const image = ogImageFor(path, title);
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: { ...baseOpenGraph, title: fullTitle, description, url: path, images: [image] },
    twitter: { ...baseTwitter, title: fullTitle, description, images: [image] },
  };
}
