import type { MetadataRoute } from 'next';
import {
  APP_HOME_PATH,
  BACKGROUND_COLOR,
  SITE_DESCRIPTION,
  SITE_NAME,
  THEME_COLOR,
} from '@/lib/config/site';
import {
  FAVICON_SVG,
  MASKABLE_ICON_PNGS,
  MONOCHROME_ICON_PNG,
  PWA_ICON_PNGS,
  pngSizes,
} from '@/lib/brand/assets';

// Served at /manifest.webmanifest; next.config.ts rewrites /manifest.json and
// /site.webmanifest here too. Icons are generated by `npm run brand:assets`.
export default function manifest(): MetadataRoute.Manifest {
  const shortcutIcon = [{ src: '/icons/icon-96x96.png', sizes: '96x96', type: 'image/png' }];

  return {
    id: '/',
    name: SITE_NAME,
    short_name: SITE_NAME,
    description: SITE_DESCRIPTION,
    start_url: APP_HOME_PATH,
    scope: '/',
    display: 'standalone',
    display_override: ['window-controls-overlay', 'standalone'],
    background_color: BACKGROUND_COLOR,
    theme_color: THEME_COLOR,
    lang: 'en',
    dir: 'ltr',
    categories: ['business', 'productivity'],
    icons: [
      { src: FAVICON_SVG, sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
      ...PWA_ICON_PNGS.map((icon) => ({
        src: icon.path,
        sizes: pngSizes(icon),
        type: 'image/png',
        purpose: 'any' as const,
      })),
      ...MASKABLE_ICON_PNGS.map((icon) => ({
        src: icon.path,
        sizes: pngSizes(icon),
        type: 'image/png',
        purpose: 'maskable' as const,
      })),
      {
        src: MONOCHROME_ICON_PNG.path,
        sizes: pngSizes(MONOCHROME_ICON_PNG),
        type: 'image/png',
        purpose: 'monochrome',
      },
    ],
    shortcuts: [
      { name: 'New Lead', short_name: 'New Lead', url: '/lead-ingestion', icons: shortcutIcon },
      { name: 'Drafts', short_name: 'Drafts', url: '/lead-ingestion/emails', icons: shortcutIcon },
      { name: 'Campaigns', short_name: 'Campaigns', url: '/lead-ingestion/campaigns', icons: shortcutIcon },
    ],
  };
}
